services:
  - type: web
    name: june-x-ultra
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        value: Ultra-X:~<base64>  # Replace with your actual session string
      - key: NODE_VERSION
        value: 20
